= API generator

The generator can generate different versions of methods for changes and preconditions by taking
the method and parameter definitions (parameter name, type, order) from `dbchangelog-latest.xsd`
(1st command line parameter)
The output files are generated by default in the folder where the generator is executed

== Overview
2 element group definitions are used: `ChangeSetChildren` and `PreConditionChildren`. The
extracted element definitions are passed to the `...templ.groovy` templates generating traits with
the same name. These traits can be implemented by the `ChangeSetDelegate` and `PreConditionDelegate`
classes respectively.

The order of the parameters is taken from the XSD, but
- required parameters are moved in front of the parameter list
- the closure parameter (if any) for children is always the last

Multiple method definitions with different parameters are generated for elements having mutually
exclusive parameters. e.g.:
- `dropColumn` : `columNames` attribute / `columns` closure with children
- `createProcedure`:  `path` / `procedureText` closure
